name: ayush_s_application5
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansRomanMedium.ttf
          weight: 500
    - family: Avenir
      fonts: 
        - asset: assets/fonts/AvenirHeavy.ttf
          weight: 800
        - asset: assets/fonts/AvenirMedium.ttf
          weight: 500
        - asset: assets/fonts/AvenirRoman.ttf
          weight: 400
